### ISSUE TITLE
Code coverage seems to be broken in version 17.10.0

### ISSUE THREAD

**Issue by norbert-groen** [microsoft/codecoverage#122]
## Description
In our CI pipeline in Azure Devops (on premise), we use the latest stable Visual Studio test platform (currently 17.10.0):
Although CodeCoverage states:
```
CodeCoverage.exe is deprecated. Use dotnet-coverage global tool or Microsoft.CodeCoverage.Console instead. Some features of CodeCoverage.exe will be removed in next release of Visual Studio.
```
Azure Devops seems to use this tool. The code coverage is broken and does not represent proper coverage anymore.
Another tool, that  is using this tool, is Sonarqube (our code quality gateway).
These errors appears:
```
##[error]Failed to convert the binary code coverage reports to XML. No code coverage information will be uploaded to the server (SonarQube/SonarCloud).
##[error]Check that the downloaded code coverage file (D:\azagent-p\A1\_work\_temp\11e7728a-01e7-4ae5-a924-a480fa3e0087\<---->_2024-05-27.18_12_16.coverage) is valid by opening it in Visual Studio. If it is not, check that the internet security settings on the build machine allow files to be downloaded from the Team Foundation Server machine.
```
and the gateway fails. This results in impossibility to merge code via pull requests, while the gateway is mandatory.
Visual studio can interpret the coverage, but it doesn't represent the proper coverage.

## Steps to reproduce
Use the latest stable version in a CI pipeline
 ```
  displayName: 'Visual Studio Test Platform Installer'
   inputs:
     packageFeedSelector: 'nugetOrg'
     versionSelector: 'latestStable'
```
and compare the code coverage against the same pipeline, but run with configuration:
 ```
  displayName: 'Visual Studio Test Platform Installer'
   inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'specificVersion'
    testPlatformVersion: '17.9.0'
```
## Expected behavior
Good representation of code coverage. External tools should be able to interpret coverage results.

## Actual behavior
Missing parts of coverage and external tools unable to interpret results. 

## Environment
Running agent on Windows: 10.0.17763
Current agent version: '3.225.2'
