### ISSUE TITLE
Microsoft.CodeCoverage 17.5.0 causes errors in Datacollection in Azure DevOps pipeline with vstest.console.exe

### ISSUE THREAD

**Issue by dlwrkk** [microsoft/codecoverage#13]
## Description

When running a DevOps pipeline with vstest@2 task on projects referencing (directly or indirectly for example thru Microsoft.NET.Test.Sdk 17.5.0) Microsoft.CodeCoverage nuget v17.5.0 with datacollector://Microsoft/CodeCoverage/2.0, DataCollection (generation of the .coverage attachment) fails. Happens if no TestAdaptersPath in runsettings or command line (pathToCustomTestAdapters).

What happens is
- the root directory of the build is added to the search path/TestAdaptersPath implicitly
- Microsoft.CodeCoverage gets restored to packages directory below the root folder of the build
- Microsoft.CodeCoverage 17.5.0 contains Microsoft.VisualStudio.TraceDataCollector in build directory
- DataCollector.exe walks thru the local folders and tries to load Microsoft.VisualStudio.TraceDataCollector from Microsoft.CodeCoverage\17.5.0\ ... \build
- Microsoft.VisualStudio.TraceDataCollector references Microsoft.CodeCoverage.Telemetry which is missing from the nuget and cannot be loaded
- load fails

this seems to be a mixture of the nuget package Microsoft.CodeCoverage missing referenced assemblies and the - strange - way datacollector.exe tries to load extensions.

**Comment by jakubch1** [comment]
@dlwrkk I am not able to reproduce this issue. Could you please provide logs (`/Diag:log.txt`) and version of Microsoft.TestPlatform you use?

**Comment by dlwrkk** [comment]
Hi, I am a bit unsure about the whole setup (didn't mess it up myself).

The test project is SDK Style, targets net48, references Microsoft.NET.Test.Sdk 17.5 (and NUnit3TestAdapter 4.4.0). No other nugets (TestPlatform or CodeCoverage) referenced

The TestPlatform seems to be loaded from  %ProgramFiles%\VS2019\Common7\IDE\Extensions\TestPlatform

Test executes using VSTest@2 Task

The TestPlatform.ObjectModel assembly seems to be 15.0.0.0

**Comment by dlwrkk** [comment]
doesn't seem to make a difference if I reference the latest 17.5 Microsoft.TestPlatform nuget in the project. Same behaviour

**Comment by jakubch1** [comment]
Please try to use this task to get latest Microsoft.TestPlatform package before vstest@2 task: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/visual-studio-test-platform-installer-v1?view=azure-pipelines. Referencing in project doesn't change anything

**Comment by dlwrkk** [comment]
Same behaviour as before. No .coverage attachment.
Same load error in datacollector log as before

**Comment by dlwrkk** [comment]
any way to prevent TraceDataCollector.dll to be loaded from the packages folder (Microsoft.CodeCoverage)?

**Comment by dlwrkk** [comment]
If Microsoft.CodeCoverage contains the TraceDataCollector assembly and is missing referenced assemblies, how is it supposed to successfully load it? Microsoft.CodeCoverage.Telemetry?

**Comment by jakubch1** [comment]
CLR loads dependency when it is needed. We added try catch to fallback and continue if missing. This is why I need logs because I see such behavior locally.

**Comment by jakubch1** [comment]
I've tried to reproduce the issue by running on Azure DevOps pool windows-2019 (VS 2019) net48 test project using Microsoft.TestPlatform version 16.11.0 (VS 2019). DataCollector.exe loaded TraceDataCollector.dll from Microsoft.CodeCoverage 17.5.0. All worked good. What pool do you use in Azure DevOps? What exact version of VS 2019 do you have installed in the agent? Do you use any runsettings?

**Comment by dlwrkk** [comment]
which part of which log do you need? The datacollector log or the test stage?

**Comment by jakubch1** [comment]
Please follow this to collect logs: https://github.com/microsoft/vstest/blob/main/docs/troubleshooting.md#azure-devops

**Comment by dlwrkk** [comment]
It must be environment related but I don't understand where the difference in behavior originates.

the vsts log says
vstest.console.exe version 16.7.0

yes, we use runsettings

agent version seem to b
[logs.zip](https://github.com/microsoft/codecoverage/files/10957494/logs.zip)
e 2.213.2 and 2.214.1

**Comment by jakubch1** [comment]
Thanks! I've changed version to 16.7.0 and finally I was able to reproduce issue. To fix issue please install latest version of Test Platform by adding:

```
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg' # 'nugetOrg' | 'customFeed' | 'netShare'. Required. Package Feed. Default: nugetOrg.
    versionSelector: 'specificVersion' # 'latestPreRelease' | 'latestStable' | 'specificVersion'. Required when packageFeedSelector = nugetOrg || packageFeedSelector = customFeed. Version. Default: latestPreRelease.
    testPlatformVersion: '17.5.0'
```

It should be added just before `VSTest@2`. Then modify `VSTest@2` by adding
```
- task: VSTest@2
  inputs:
    vstestLocationMethod: 'version'
    vsTestVersion: 'toolsInstaller'
```

Even version `16.11.0` is fixing issue.
