### ISSUE TITLE
Issue with Code Complexity Discrepancy in Cobertura Report

### ISSUE THREAD

**Issue by peterm28** [microsoft/codecoverage#35]
**Description:**
Hello everyone,

I've encountered an issue related to code coverage in our project. Specifically, I've noticed a discrepancy between the cyclomatic complexity reported by our pipeline task and the complexity displayed in Visual Studio.

**Problem Description:**
When running one of our unit test suites, I noticed that a complex method in one of the tested classes is being shown as having a cyclomatic complexity of 1 in the coverage report generated by the pipeline. However, when I perform the same analysis in Visual Studio, the complexity of the method is displayed as 50.

**Investigation Efforts:**
I have been trying to search for a possible open issue online, but I have not been successful. I have attached the pipeline task responsible for running the unit test suite. I can also privately share the relevant class and Cobertura.xml if it would be of any use. Initially, I thought that the issue may be in the pipeline task itself. However, I attempted to collect the coverage locally through `vstest.console.exe` and encountered the same result. I've also tried to collect complexity for other test suites using the `dotnet test` command, and for the methods in those tested classes, the complexity was either the same or very similar to the one reported by Visual Studio.

```
vstest.console.exe .\NotificationHub\TransitionalTools.Tests\bin\Debug\TransitionalTools.Tests.dll /collect:"Code Coverage;Format=Cobertura" /settings:.\NotificationHub\TransitionalTools.Tests\coverage.runsettings
```

```
- task: VSTest@2
  displayName: 'Test transitional tools'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: 'TransitionalTools.Tests.dll'
    searchFolder: 'NotificationHub\TransitionalTools.Tests\bin\Release\'
    runInParallel: false
    otherConsoleOptions: '/collect:"Code Coverage;Format=Cobertura"'
    runsettingsFile: 'NotificationHub\TransitionalTools.Tests\coverage.runsettings'
    codeCoverageEnabled: true
    resultsFolder: '$(Agent.TempDirectory)\TestResults'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    publishRunAttachments: false
    failOnMinTestsNotRun: true
    minimumExpectedTests: '350'
```

**Issue Details:**
Looking at the Cobertura report, the branches (switch statements, if-statements, loops,...) in the covered method are not acknowledged.

Thank you all for your attention and assistance in advance.

Kind regards,
Peter
